/*
 * SCIM 2.0 APIs Documentation
 * SCIM 2.0 APIs Documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@wso2.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Scimv2ServiceProviderConfigApi
 */
@Ignore
public class Scimv2ServiceProviderConfigApiTest {

    private final Scimv2ServiceProviderConfigApi api = new Scimv2ServiceProviderConfigApi();

    
    /**
     * Return the ServiceProviderConfig schema.
     *
     * Returns HTTP 200 if the schema is found.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getServiceProviderConfigTest() throws ApiException {
        api.getServiceProviderConfig();

        // TODO: test validations
    }
    
}
