/*
 * SCIM 2.0 APIs Documentation
 * SCIM 2.0 APIs Documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@wso2.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Scimv2BulkApi
 */
@Ignore
public class Scimv2BulkApiTest {

    private final Scimv2BulkApi api = new Scimv2BulkApi();

    
    /**
     * Return the bulk which was created.
     *
     * Returns HTTP 201 if the bulk is successfully created.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createBulkTest() throws ApiException {
        List<String> attributes = null;
        List<String> excludedAttributes = null;
        String body = null;
        api.createBulk(attributes, excludedAttributes, body);

        // TODO: test validations
    }
    
}
