/*
 * SCIM 2.0 APIs Documentation
 * SCIM 2.0 APIs Documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@wso2.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Scimv2MeApi
 */
@Ignore
public class Scimv2MeApiTest {

    private final Scimv2MeApi api = new Scimv2MeApi();

    
    /**
     * Return the user which was anonymously created
     *
     * Returns HTTP 201 if the user is successfully created.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createMeTest() throws ApiException {
        List<String> attributes = null;
        List<String> excludedAttributes = null;
        String body = null;
        api.createMe(attributes, excludedAttributes, body);

        // TODO: test validations
    }
    
    /**
     * Delete the authenticated user.
     *
     * Returns HTTP 204 if the user is successfully deleted.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteMeTest() throws ApiException {
        api.deleteMe();

        // TODO: test validations
    }
    
    /**
     * Return the authenticated user.
     *
     * Returns HTTP 200 if the user is found.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMeTest() throws ApiException {
        List<String> attributes = null;
        List<String> excludedAttributes = null;
        api.getMe(attributes, excludedAttributes);

        // TODO: test validations
    }
    
    /**
     * Return the updated user
     *
     * Returns HTTP 404 if the user is not found.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateMeTest() throws ApiException {
        List<String> attributes = null;
        List<String> excludedAttributes = null;
        String body = null;
        api.updateMe(attributes, excludedAttributes, body);

        // TODO: test validations
    }
    
}
